a

diff --git a/.github/workflows/ci-dotnet.yml b/.github/workflows/ci-dotnet.yml
--- a/.github/workflows/ci-dotnet.yml
+++ b/.github/workflows/ci-dotnet.yml
@@ -36,15 +36,16 @@ jobs:
 
       - name: Convert coverage to HTML
         env:
-          PATH: ${{ env.PATH }}:$HOME/.dotnet/tools
+            PATH: ${{ env.PATH }}:$HOME/.dotnet/tools
         run: |
-          mkdir -p coverage-report
-          COVERAGE_FILE=$(find ./TestResults -name 'coverage.cobertura.xml' | head -n 1 || true)
-          if [ -z "$COVERAGE_FILE" ]; then
-            echo "Coverage file not found in ./TestResults"
-            exit 0
-          fi
-          reportgenerator -reports:$COVERAGE_FILE -targetdir:coverage-report -reporttypes:Html
+            mkdir -p coverage-report
+            COVERAGE_FILE=$(find ./TestResults -name 'coverage.cobertura.xml' | head -n 1 || true)
+            if [ -z "$COVERAGE_FILE" ]; then
+                echo "Coverage file not found in ./TestResults"
+                exit 0
+            fi
+            reportgenerator -reports:$COVERAGE_FILE -targetdir:coverage-report -reporttypes:Html
+            shell: bash
 
       - name: Upload coverage artifact
         uses: actions/upload-artifact@v4
